# Copyright 2025 WAFlash-ReFlexed Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

EMCC = emcc
CXXFLAGS = -O2 -std=c++17 -Isrc
EXPORTED_FUNCTIONS = '["_main","_Play","_Stop","_reopenBuffer","_invokeExternalCallback","_malloc","_free","_strlen"]'
EXPORTED_RUNTIME = '["ccall","cwrap","FS"]'

WASM_FLAGS = \
    -s WASM=1 \
    -s INITIAL_MEMORY=16777216 \
    -s MAXIMUM_MEMORY=2147483648 \
    -s ALLOW_MEMORY_GROWTH=1 \
    -s EXPORTED_FUNCTIONS=$(EXPORTED_FUNCTIONS) \
    -s EXPORTED_RUNTIME_METHODS=$(EXPORTED_RUNTIME) \
    -s USE_WEBGL2=1 \
    -s USE_ZLIB=1 \
    -s USE_LIBLZMA=1 \
    -lz \
    -DHAS_AVMPLUS=0

SOURCES = \
    src/main.cpp \
    src/core/engine.cpp \
    src/core/play_stop.cpp \
    src/core/memfs.cpp \
    src/avm/avm2.cpp \
    src/render/webgl_renderer.cpp \
    src/render/canvas_renderer.cpp \
    src/audio/audio.cpp \
    src/bridge/external_interface.cpp \
    src/memory/allocator.cpp

all:
	mkdir -p dist
	$(EMCC) $(CXXFLAGS) $(WASM_FLAGS) $(SOURCES) -o dist/waflash-reflexed.js

clean:
	rm -rf dist/waflash-reflexed.js dist/waflash-reflexed.wasm
