EMCC     = emcc
CXX_STD  = -std=c++17
OPT      = -O2
OUTDIR   = dist

SOURCES  = \
  src/core/engine.cpp \
  src/core/play_stop.cpp \
  src/core/memfs.cpp \
  src/avm/avm2.cpp \
  src/avm/movie_clip.cpp \
  src/swf/swf_loader.cpp \
  src/render/webgl_renderer.cpp \
  src/render/canvas_renderer.cpp \
  src/audio/audio.cpp \
  src/bridge/external_interface.cpp \
  src/memory/allocator.cpp \
  src/main.cpp

INCLUDES = -Isrc/

EXPORTED_FUNCTIONS = '["_main","_Play","_Stop","_engine_tick","_reopenBuffer","_invokeExternalCallback","_malloc","_free","_strlen"]'
EXPORTED_RUNTIME   = '["ccall","cwrap","FS","MEMFS"]'

WASM_FLAGS = \
  -s WASM=1 \
  -s INITIAL_MEMORY=16777216 \
  -s MAXIMUM_MEMORY=2147483648 \
  -s ALLOW_MEMORY_GROWTH=1 \
  -s USE_ZLIB=1 \
  -s USE_WEBGL2=1 \
  -s EXPORTED_FUNCTIONS=$(EXPORTED_FUNCTIONS) \
  -s EXPORTED_RUNTIME_METHODS=$(EXPORTED_RUNTIME) \
  -s ENVIRONMENT=web \
  -s MODULARIZE=0 \
  -s ASSERTIONS=0

all: $(OUTDIR)/waflash-reflexed.wasm

$(OUTDIR)/waflash-reflexed.wasm: $(SOURCES)
	mkdir -p $(OUTDIR)
	$(EMCC) $(CXX_STD) $(OPT) $(INCLUDES) $(WASM_FLAGS) \
	  $(SOURCES) \
	  -o $(OUTDIR)/waflash-reflexed.js

clean:
	rm -rf $(OUTDIR)/waflash-reflexed.js \
	       $(OUTDIR)/waflash-reflexed.wasm

.PHONY: all clean
