EMCC    = emcc
OPT     = -O2
OUTDIR  = dist

SOURCES = \
  src/main.cpp \
  src/core/engine.cpp \
  src/core/play_stop.cpp \
  src/core/memfs.cpp \
  src/avm/avm2.cpp \
  src/avm/movie_clip.cpp \
  src/swf/swf_loader.cpp \
  src/swf/swf_tags.cpp \
  src/render/webgl_renderer.cpp \
  src/render/canvas_renderer.cpp \
  src/render/display_list.cpp \
  src/audio/audio.cpp \
  src/bridge/external_interface.cpp \
  src/memory/allocator.cpp

EXPORTED_FUNCTIONS = '["_main","_Play","_Stop","_engine_tick","_reopenBuffer","_invokeExternalCallback","_malloc","_free","_strlen","_setBackgroundColor","_getBackgroundColor","_isFrameReady","_signalFrameReady","_setSWFDimensions","_getSWFWidth","_getSWFHeight"]'
EXPORTED_RUNTIME   = '["ccall","cwrap","FS","MEMFS"]'

FLAGS = \
  -std=c++17 \
  -s WASM=1 \
  -s INITIAL_MEMORY=16777216 \
  -s MAXIMUM_MEMORY=2147483648 \
  -s ALLOW_MEMORY_GROWTH=1 \
  -s USE_ZLIB=1 \
  -s USE_WEBGL2=1 \
  -s EXPORTED_FUNCTIONS=$(EXPORTED_FUNCTIONS) \
  -s EXPORTED_RUNTIME_METHODS=$(EXPORTED_RUNTIME) \
  -s ENVIRONMENT=web \
  -s MODULARIZE=0 \
  -s EXPORT_NAME=Module \
  -s ASSERTIONS=1 \
  -s NO_EXIT_RUNTIME=1 \
  -Isrc/

all:
	mkdir -p $(OUTDIR)
	$(EMCC) $(OPT) $(FLAGS) $(SOURCES) -o $(OUTDIR)/waflash-reflexed.js
	@echo "Build complete: $(OUTDIR)/waflash-reflexed.wasm"

clean:
	rm -f $(OUTDIR)/waflash-reflexed.js $(OUTDIR)/waflash-reflexed.wasm

.PHONY: all clean
